# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Israa S.D
title: Physicist | Programmer
email: israasaifullah@gmail.com
website: http://hibee.ml

# Social links
# twitter_username: facespics
github_username:  QuantMis
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: israaibnusaifullah
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  UM Physicist with high mathematics proficiency, knowledgable in FinTech (Cryptocurrencies) & Stock Market, have employment records from small tech startup to major investment banks, programmer with solid development portfolio
  encompassing automation scripting, web application and machine learning.
  
  Highlights: 
    - Python, Cython for backend scripting.
    - Linux Server (Ubuntu, CentOS) management for app deployment.
    - Full stack web Application via flask, nginx & uwsgi. 
    - Mongo and Sql Database. 
    - pureJS, Jquery, HTML and CSS for UI design and functionalities.
    - Machine learning via Python Keras and Scipy for development of Neural Network (LSTMs).
   
# More Section
# more_title: A Little More About Me
#more_content: | # this will include new lines to allow paragraphs
#  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#   - Rock climbing
#   - Gaming
#   - Knitting
#   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education


# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
